#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from dlang.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "dlang.y"

#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#define YYERROR_VERBOSE

int yylex();
int yyerror(char const *s);

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	T_abstract	258
#define	T_alias	259
#define	T_align	260
#define	T_asm	261
#define	T_assert	262
#define	T_auto	263
#define	T_body	264
#define	T_bool	265
#define	T_break	266
#define	T_byte	267
#define	T_case	268
#define	T_cast	269
#define	T_catch	270
#define	T_cdouble	271
#define	T_cent	272
#define	T_cfloat	273
#define	T_char	274
#define	T_class	275
#define	T_const	276
#define	T_continue	277
#define	T_creal	278
#define	T_dchar	279
#define	T_debug	280
#define	T_default	281
#define	T_delegate	282
#define	T_deprecated	283
#define	T_do	284
#define	T_double	285
#define	T_else	286
#define	T_enum	287
#define	T_export	288
#define	T_extern	289
#define	T_false	290
#define	T_final	291
#define	T_finally	292
#define	T_float	293
#define	T_for	294
#define	T_foreach	295
#define	T_foreach_reverse	296
#define	T_function	297
#define	T_goto	298
#define	T_idouble	299
#define	T_if	300
#define	T_ifloat	301
#define	T_immutable	302
#define	T_import	303
#define	T_in	304
#define	T_inout	305
#define	T_int	306
#define	T_interface	307
#define	T_invariant	308
#define	T_ireal	309
#define	T_is	310
#define	T_lazy	311
#define	T_long	312
#define	T_mixin	313
#define	T_module	314
#define	T_new	315
#define	T_nothrow	316
#define	T_null	317
#define	T_out	318
#define	T_override	319
#define	T_package	320
#define	T_pragma	321
#define	T_private	322
#define	T_protected	323
#define	T_public	324
#define	T_pure	325
#define	T_real	326
#define	T_ref	327
#define	T_return	328
#define	T_scope	329
#define	T_shared	330
#define	T_short	331
#define	T_static	332
#define	T_struc	333
#define	T_super	334
#define	T_switch	335
#define	T_synchronized	336
#define	T_template	337
#define	T_this	338
#define	T_throw	339
#define	T_true	340
#define	T_try	341
#define	T_typeid	342
#define	T_typeof	343
#define	T_ubyte	344
#define	T_ucent	345
#define	T_uint	346
#define	T_ulong	347
#define	T_union	348
#define	T_unittest	349
#define	T_ushort	350
#define	T_version	351
#define	T_void	352
#define	T_wchar	353
#define	T_while	354
#define	T_with	355
#define	NUM	356
#define	T_neq	357
#define	T_bslash	358
#define	T_land	359
#define	T_andeq	360
#define	T_and	361
#define	T_lor	362
#define	T_oreq	363
#define	T_or	364
#define	T_dec	365
#define	T_deceq	366
#define	T_minus	367
#define	T_inc	368
#define	T_inceq	369
#define	T_plus	370
#define	T_GEQ	371
#define	T_GR	372
#define	T_NOTEQ	373
#define	T_OPAREN	374
#define	T_CPAREN	375
#define	T_OCOR	376
#define	T_CCOR	377
#define	T_SEMICOLON	378
#define	T_EQUAL	379
#define	T_multiply	380
#define	T_COMA	381
#define	T_LE	382
#define	T_isEqual	383
#define	DEC	384
#define	ID	385
#define	T_LT	386
#define	END_OF_FILE	387
#define	T_multeq	388
#define	T_LITCHAR	389
#define	T_dot	390
#define	T_COLON	391
#define	T_LSTRING	392


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int T_abstract;
static const int T_alias;
static const int T_align;
static const int T_asm;
static const int T_assert;
static const int T_auto;
static const int T_body;
static const int T_bool;
static const int T_break;
static const int T_byte;
static const int T_case;
static const int T_cast;
static const int T_catch;
static const int T_cdouble;
static const int T_cent;
static const int T_cfloat;
static const int T_char;
static const int T_class;
static const int T_const;
static const int T_continue;
static const int T_creal;
static const int T_dchar;
static const int T_debug;
static const int T_default;
static const int T_delegate;
static const int T_deprecated;
static const int T_do;
static const int T_double;
static const int T_else;
static const int T_enum;
static const int T_export;
static const int T_extern;
static const int T_false;
static const int T_final;
static const int T_finally;
static const int T_float;
static const int T_for;
static const int T_foreach;
static const int T_foreach_reverse;
static const int T_function;
static const int T_goto;
static const int T_idouble;
static const int T_if;
static const int T_ifloat;
static const int T_immutable;
static const int T_import;
static const int T_in;
static const int T_inout;
static const int T_int;
static const int T_interface;
static const int T_invariant;
static const int T_ireal;
static const int T_is;
static const int T_lazy;
static const int T_long;
static const int T_mixin;
static const int T_module;
static const int T_new;
static const int T_nothrow;
static const int T_null;
static const int T_out;
static const int T_override;
static const int T_package;
static const int T_pragma;
static const int T_private;
static const int T_protected;
static const int T_public;
static const int T_pure;
static const int T_real;
static const int T_ref;
static const int T_return;
static const int T_scope;
static const int T_shared;
static const int T_short;
static const int T_static;
static const int T_struc;
static const int T_super;
static const int T_switch;
static const int T_synchronized;
static const int T_template;
static const int T_this;
static const int T_throw;
static const int T_true;
static const int T_try;
static const int T_typeid;
static const int T_typeof;
static const int T_ubyte;
static const int T_ucent;
static const int T_uint;
static const int T_ulong;
static const int T_union;
static const int T_unittest;
static const int T_ushort;
static const int T_version;
static const int T_void;
static const int T_wchar;
static const int T_while;
static const int T_with;
static const int NUM;
static const int T_neq;
static const int T_bslash;
static const int T_land;
static const int T_andeq;
static const int T_and;
static const int T_lor;
static const int T_oreq;
static const int T_or;
static const int T_dec;
static const int T_deceq;
static const int T_minus;
static const int T_inc;
static const int T_inceq;
static const int T_plus;
static const int T_GEQ;
static const int T_GR;
static const int T_NOTEQ;
static const int T_OPAREN;
static const int T_CPAREN;
static const int T_OCOR;
static const int T_CCOR;
static const int T_SEMICOLON;
static const int T_EQUAL;
static const int T_multiply;
static const int T_COMA;
static const int T_LE;
static const int T_isEqual;
static const int DEC;
static const int ID;
static const int T_LT;
static const int END_OF_FILE;
static const int T_multeq;
static const int T_LITCHAR;
static const int T_dot;
static const int T_COLON;
static const int T_LSTRING;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,T_abstract=258
	,T_alias=259
	,T_align=260
	,T_asm=261
	,T_assert=262
	,T_auto=263
	,T_body=264
	,T_bool=265
	,T_break=266
	,T_byte=267
	,T_case=268
	,T_cast=269
	,T_catch=270
	,T_cdouble=271
	,T_cent=272
	,T_cfloat=273
	,T_char=274
	,T_class=275
	,T_const=276
	,T_continue=277
	,T_creal=278
	,T_dchar=279
	,T_debug=280
	,T_default=281
	,T_delegate=282
	,T_deprecated=283
	,T_do=284
	,T_double=285
	,T_else=286
	,T_enum=287
	,T_export=288
	,T_extern=289
	,T_false=290
	,T_final=291
	,T_finally=292
	,T_float=293
	,T_for=294
	,T_foreach=295
	,T_foreach_reverse=296
	,T_function=297
	,T_goto=298
	,T_idouble=299
	,T_if=300
	,T_ifloat=301
	,T_immutable=302
	,T_import=303
	,T_in=304
	,T_inout=305
	,T_int=306
	,T_interface=307
	,T_invariant=308
	,T_ireal=309
	,T_is=310
	,T_lazy=311
	,T_long=312
	,T_mixin=313
	,T_module=314
	,T_new=315
	,T_nothrow=316
	,T_null=317
	,T_out=318
	,T_override=319
	,T_package=320
	,T_pragma=321
	,T_private=322
	,T_protected=323
	,T_public=324
	,T_pure=325
	,T_real=326
	,T_ref=327
	,T_return=328
	,T_scope=329
	,T_shared=330
	,T_short=331
	,T_static=332
	,T_struc=333
	,T_super=334
	,T_switch=335
	,T_synchronized=336
	,T_template=337
	,T_this=338
	,T_throw=339
	,T_true=340
	,T_try=341
	,T_typeid=342
	,T_typeof=343
	,T_ubyte=344
	,T_ucent=345
	,T_uint=346
	,T_ulong=347
	,T_union=348
	,T_unittest=349
	,T_ushort=350
	,T_version=351
	,T_void=352
	,T_wchar=353
	,T_while=354
	,T_with=355
	,NUM=356
	,T_neq=357
	,T_bslash=358
	,T_land=359
	,T_andeq=360
	,T_and=361
	,T_lor=362
	,T_oreq=363
	,T_or=364
	,T_dec=365
	,T_deceq=366
	,T_minus=367
	,T_inc=368
	,T_inceq=369
	,T_plus=370
	,T_GEQ=371
	,T_GR=372
	,T_NOTEQ=373
	,T_OPAREN=374
	,T_CPAREN=375
	,T_OCOR=376
	,T_CCOR=377
	,T_SEMICOLON=378
	,T_EQUAL=379
	,T_multiply=380
	,T_COMA=381
	,T_LE=382
	,T_isEqual=383
	,DEC=384
	,ID=385
	,T_LT=386
	,END_OF_FILE=387
	,T_multeq=388
	,T_LITCHAR=389
	,T_dot=390
	,T_COLON=391
	,T_LSTRING=392


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::T_abstract=258;
const int YY_parse_CLASS::T_alias=259;
const int YY_parse_CLASS::T_align=260;
const int YY_parse_CLASS::T_asm=261;
const int YY_parse_CLASS::T_assert=262;
const int YY_parse_CLASS::T_auto=263;
const int YY_parse_CLASS::T_body=264;
const int YY_parse_CLASS::T_bool=265;
const int YY_parse_CLASS::T_break=266;
const int YY_parse_CLASS::T_byte=267;
const int YY_parse_CLASS::T_case=268;
const int YY_parse_CLASS::T_cast=269;
const int YY_parse_CLASS::T_catch=270;
const int YY_parse_CLASS::T_cdouble=271;
const int YY_parse_CLASS::T_cent=272;
const int YY_parse_CLASS::T_cfloat=273;
const int YY_parse_CLASS::T_char=274;
const int YY_parse_CLASS::T_class=275;
const int YY_parse_CLASS::T_const=276;
const int YY_parse_CLASS::T_continue=277;
const int YY_parse_CLASS::T_creal=278;
const int YY_parse_CLASS::T_dchar=279;
const int YY_parse_CLASS::T_debug=280;
const int YY_parse_CLASS::T_default=281;
const int YY_parse_CLASS::T_delegate=282;
const int YY_parse_CLASS::T_deprecated=283;
const int YY_parse_CLASS::T_do=284;
const int YY_parse_CLASS::T_double=285;
const int YY_parse_CLASS::T_else=286;
const int YY_parse_CLASS::T_enum=287;
const int YY_parse_CLASS::T_export=288;
const int YY_parse_CLASS::T_extern=289;
const int YY_parse_CLASS::T_false=290;
const int YY_parse_CLASS::T_final=291;
const int YY_parse_CLASS::T_finally=292;
const int YY_parse_CLASS::T_float=293;
const int YY_parse_CLASS::T_for=294;
const int YY_parse_CLASS::T_foreach=295;
const int YY_parse_CLASS::T_foreach_reverse=296;
const int YY_parse_CLASS::T_function=297;
const int YY_parse_CLASS::T_goto=298;
const int YY_parse_CLASS::T_idouble=299;
const int YY_parse_CLASS::T_if=300;
const int YY_parse_CLASS::T_ifloat=301;
const int YY_parse_CLASS::T_immutable=302;
const int YY_parse_CLASS::T_import=303;
const int YY_parse_CLASS::T_in=304;
const int YY_parse_CLASS::T_inout=305;
const int YY_parse_CLASS::T_int=306;
const int YY_parse_CLASS::T_interface=307;
const int YY_parse_CLASS::T_invariant=308;
const int YY_parse_CLASS::T_ireal=309;
const int YY_parse_CLASS::T_is=310;
const int YY_parse_CLASS::T_lazy=311;
const int YY_parse_CLASS::T_long=312;
const int YY_parse_CLASS::T_mixin=313;
const int YY_parse_CLASS::T_module=314;
const int YY_parse_CLASS::T_new=315;
const int YY_parse_CLASS::T_nothrow=316;
const int YY_parse_CLASS::T_null=317;
const int YY_parse_CLASS::T_out=318;
const int YY_parse_CLASS::T_override=319;
const int YY_parse_CLASS::T_package=320;
const int YY_parse_CLASS::T_pragma=321;
const int YY_parse_CLASS::T_private=322;
const int YY_parse_CLASS::T_protected=323;
const int YY_parse_CLASS::T_public=324;
const int YY_parse_CLASS::T_pure=325;
const int YY_parse_CLASS::T_real=326;
const int YY_parse_CLASS::T_ref=327;
const int YY_parse_CLASS::T_return=328;
const int YY_parse_CLASS::T_scope=329;
const int YY_parse_CLASS::T_shared=330;
const int YY_parse_CLASS::T_short=331;
const int YY_parse_CLASS::T_static=332;
const int YY_parse_CLASS::T_struc=333;
const int YY_parse_CLASS::T_super=334;
const int YY_parse_CLASS::T_switch=335;
const int YY_parse_CLASS::T_synchronized=336;
const int YY_parse_CLASS::T_template=337;
const int YY_parse_CLASS::T_this=338;
const int YY_parse_CLASS::T_throw=339;
const int YY_parse_CLASS::T_true=340;
const int YY_parse_CLASS::T_try=341;
const int YY_parse_CLASS::T_typeid=342;
const int YY_parse_CLASS::T_typeof=343;
const int YY_parse_CLASS::T_ubyte=344;
const int YY_parse_CLASS::T_ucent=345;
const int YY_parse_CLASS::T_uint=346;
const int YY_parse_CLASS::T_ulong=347;
const int YY_parse_CLASS::T_union=348;
const int YY_parse_CLASS::T_unittest=349;
const int YY_parse_CLASS::T_ushort=350;
const int YY_parse_CLASS::T_version=351;
const int YY_parse_CLASS::T_void=352;
const int YY_parse_CLASS::T_wchar=353;
const int YY_parse_CLASS::T_while=354;
const int YY_parse_CLASS::T_with=355;
const int YY_parse_CLASS::NUM=356;
const int YY_parse_CLASS::T_neq=357;
const int YY_parse_CLASS::T_bslash=358;
const int YY_parse_CLASS::T_land=359;
const int YY_parse_CLASS::T_andeq=360;
const int YY_parse_CLASS::T_and=361;
const int YY_parse_CLASS::T_lor=362;
const int YY_parse_CLASS::T_oreq=363;
const int YY_parse_CLASS::T_or=364;
const int YY_parse_CLASS::T_dec=365;
const int YY_parse_CLASS::T_deceq=366;
const int YY_parse_CLASS::T_minus=367;
const int YY_parse_CLASS::T_inc=368;
const int YY_parse_CLASS::T_inceq=369;
const int YY_parse_CLASS::T_plus=370;
const int YY_parse_CLASS::T_GEQ=371;
const int YY_parse_CLASS::T_GR=372;
const int YY_parse_CLASS::T_NOTEQ=373;
const int YY_parse_CLASS::T_OPAREN=374;
const int YY_parse_CLASS::T_CPAREN=375;
const int YY_parse_CLASS::T_OCOR=376;
const int YY_parse_CLASS::T_CCOR=377;
const int YY_parse_CLASS::T_SEMICOLON=378;
const int YY_parse_CLASS::T_EQUAL=379;
const int YY_parse_CLASS::T_multiply=380;
const int YY_parse_CLASS::T_COMA=381;
const int YY_parse_CLASS::T_LE=382;
const int YY_parse_CLASS::T_isEqual=383;
const int YY_parse_CLASS::DEC=384;
const int YY_parse_CLASS::ID=385;
const int YY_parse_CLASS::T_LT=386;
const int YY_parse_CLASS::END_OF_FILE=387;
const int YY_parse_CLASS::T_multeq=388;
const int YY_parse_CLASS::T_LITCHAR=389;
const int YY_parse_CLASS::T_dot=390;
const int YY_parse_CLASS::T_COLON=391;
const int YY_parse_CLASS::T_LSTRING=392;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		178
#define	YYFLAG		-32768
#define	YYNTBASE	138

#define YYTRANSLATE(x) ((unsigned)(x) <= 392 ? yytranslate[x] : 169)

static const short yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64,    65,
    66,    67,    68,    69,    70,    71,    72,    73,    74,    75,
    76,    77,    78,    79,    80,    81,    82,    83,    84,    85,
    86,    87,    88,    89,    90,    91,    92,    93,    94,    95,
    96,    97,    98,    99,   100,   101,   102,   103,   104,   105,
   106,   107,   108,   109,   110,   111,   112,   113,   114,   115,
   116,   117,   118,   119,   120,   121,   122,   123,   124,   125,
   126,   127,   128,   129,   130,   131,   132,   133,   134,   135,
   136,   137
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,     9,    13,    18,    21,    25,    28,    32,
    35,    39,    41,    45,    47,    51,    53,    56,    58,    61,
    64,    67,    70,    72,    74,    76,    79,    81,    83,    86,
    89,    91,    93,    95,    97,    99,   102,   108,   114,   122,
   130,   133,   139,   144,   154,   164,   174,   184,   193,   202,
   211,   220,   224,   228,   232,   236,   240,   245,   249,   253,
   257,   261,   263,   265,   267,   269,   272,   275,   278,   280,
   282,   284,   287,   289,   293,   295,   297,   299,   301,   303,
   305,   307,   309,   311,   313,   316,   319,   321,   323,   329,
   331,   333,   335,   337,   340,   343,   347
};

static const short yyrhs[] = {   147,
     0,   146,     0,   130,   135,   130,   142,     0,   130,   135,
   130,     0,   162,   130,   143,   146,     0,   130,   142,     0,
   119,   145,   120,     0,   119,   120,     0,   119,   144,   120,
     0,   119,   120,     0,   160,   126,   144,     0,   160,     0,
   130,   126,   145,     0,   130,     0,   121,   147,   122,     0,
   149,     0,   149,   147,     0,    73,     0,    73,   150,     0,
    73,   159,     0,   150,   123,     0,   130,   123,     0,   154,
     0,   151,     0,   140,     0,   141,   123,     0,   155,     0,
   166,     0,   148,   123,     0,   139,   123,     0,   157,     0,
   160,     0,   161,     0,   164,     0,   152,     0,   152,   153,
     0,    45,   119,   156,   120,   146,     0,    45,   119,   130,
   120,   146,     0,    31,    45,   119,   156,   120,   146,   153,
     0,    31,    45,   119,   130,   120,   146,   153,     0,    31,
   146,     0,    99,   119,   156,   120,   146,     0,    99,   119,
   156,   120,     0,    39,   119,   157,   123,   156,   123,   161,
   120,   146,     0,    39,   119,   161,   123,   156,   123,   161,
   120,   146,     0,    39,   119,   157,   123,   156,   123,   164,
   120,   146,     0,    39,   119,   161,   123,   156,   123,   164,
   120,   146,     0,    39,   119,   157,   123,   156,   123,   161,
   120,     0,    39,   119,   161,   123,   156,   123,   161,   120,
     0,    39,   119,   157,   123,   156,   123,   164,   120,     0,
    39,   119,   161,   123,   156,   123,   164,   120,     0,   158,
   117,   158,     0,   158,   131,   158,     0,   158,   128,   158,
     0,   158,   104,   158,     0,   158,   107,   158,     0,   162,
   130,   163,   158,     0,   159,   115,   158,     0,   159,   112,
   158,     0,   159,   125,   158,     0,   159,   103,   158,     0,
   159,     0,   101,     0,   129,     0,   130,     0,   112,   101,
     0,   112,   129,     0,   112,   130,     0,   134,     0,   137,
     0,    62,     0,   162,   130,     0,   156,     0,   130,   163,
   158,     0,    51,     0,    30,     0,    38,     0,    10,     0,
    97,     0,   114,     0,   111,     0,   102,     0,   133,     0,
   124,     0,   130,   165,     0,   165,   130,     0,   113,     0,
   110,     0,    20,   130,   121,   168,   122,     0,    69,     0,
    67,     0,    68,     0,   140,     0,   150,   123,     0,   140,
   168,     0,   150,   123,   168,     0,   167,   136,   168,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   152,   155,   160,   162,   166,   170,   174,   176,   179,   181,
   184,   186,   189,   191,   196,   200,   202,   205,   208,   209,
   212,   214,   215,   216,   217,   218,   219,   220,   221,   222,
   225,   227,   228,   229,   232,   234,   237,   239,   242,   244,
   245,   248,   250,   252,   255,   257,   258,   260,   261,   263,
   264,   267,   269,   270,   271,   272,   275,   279,   281,   282,
   283,   284,   287,   289,   290,   291,   292,   293,   294,   295,
   296,   299,   301,   305,   308,   310,   311,   312,   313,   316,
   318,   319,   320,   321,   323,   325,   327,   329,   331,   335,
   337,   338,   340,   342,   343,   344,   345
};

static const char * const yytname[] = {   "$","error","$illegal.","T_abstract",
"T_alias","T_align","T_asm","T_assert","T_auto","T_body","T_bool","T_break",
"T_byte","T_case","T_cast","T_catch","T_cdouble","T_cent","T_cfloat","T_char",
"T_class","T_const","T_continue","T_creal","T_dchar","T_debug","T_default","T_delegate",
"T_deprecated","T_do","T_double","T_else","T_enum","T_export","T_extern","T_false",
"T_final","T_finally","T_float","T_for","T_foreach","T_foreach_reverse","T_function",
"T_goto","T_idouble","T_if","T_ifloat","T_immutable","T_import","T_in","T_inout",
"T_int","T_interface","T_invariant","T_ireal","T_is","T_lazy","T_long","T_mixin",
"T_module","T_new","T_nothrow","T_null","T_out","T_override","T_package","T_pragma",
"T_private","T_protected","T_public","T_pure","T_real","T_ref","T_return","T_scope",
"T_shared","T_short","T_static","T_struc","T_super","T_switch","T_synchronized",
"T_template","T_this","T_throw","T_true","T_try","T_typeid","T_typeof","T_ubyte",
"T_ucent","T_uint","T_ulong","T_union","T_unittest","T_ushort","T_version","T_void",
"T_wchar","T_while","T_with","NUM","T_neq","T_bslash","T_land","T_andeq","T_and",
"T_lor","T_oreq","T_or","T_dec","T_deceq","T_minus","T_inc","T_inceq","T_plus",
"T_GEQ","T_GR","T_NOTEQ","T_OPAREN","T_CPAREN","T_OCOR","T_CCOR","T_SEMICOLON",
"T_EQUAL","T_multiply","T_COMA","T_LE","T_isEqual","DEC","ID","T_LT","END_OF_FILE",
"T_multeq","T_LITCHAR","T_dot","T_COLON","T_LSTRING","prog","call_method","func_declaration",
"func_use","param_list_use","param_list_type","declaration_expression_list",
"id_list","block","expressions_list","return_somehting","expression","assign_expression",
"if_expression","init_if","else_expression","while_expression","for_expression",
"condition","type_assign_expression","operation_expression","literals","declaration_expression",
"existing_assign_expression","type","Equal_type","inc_dec_declaration","inc_dec",
"class_declaration","access_mode","attributes_func",""
};
#endif

static const short yyr1[] = {     0,
   138,   138,   139,   139,   140,   141,   142,   142,   143,   143,
   144,   144,   145,   145,   146,   147,   147,   148,   148,   148,
   149,   149,   149,   149,   149,   149,   149,   149,   149,   149,
   150,   150,   150,   150,   151,   151,   152,   152,   153,   153,
   153,   154,   154,   155,   155,   155,   155,   155,   155,   155,
   155,   156,   156,   156,   156,   156,   157,   158,   158,   158,
   158,   158,   159,   159,   159,   159,   159,   159,   159,   159,
   159,   160,   160,   161,   162,   162,   162,   162,   162,   163,
   163,   163,   163,   163,   164,   164,   165,   165,   166,   167,
   167,   167,   168,   168,   168,   168,   168
};

static const short yyr2[] = {     0,
     1,     1,     4,     3,     4,     2,     3,     2,     3,     2,
     3,     1,     3,     1,     3,     1,     2,     1,     2,     2,
     2,     2,     1,     1,     1,     2,     1,     1,     2,     2,
     1,     1,     1,     1,     1,     2,     5,     5,     7,     7,
     2,     5,     4,     9,     9,     9,     9,     8,     8,     8,
     8,     3,     3,     3,     3,     3,     4,     3,     3,     3,
     3,     1,     1,     1,     1,     2,     2,     2,     1,     1,
     1,     2,     1,     3,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     2,     2,     1,     1,     5,     1,
     1,     1,     1,     2,     2,     3,     3
};

static const short yydefact[] = {     0,
    78,     0,    76,    77,     0,     0,    75,    71,    18,    79,
     0,    63,    88,     0,    87,     0,    64,    65,    69,    70,
     0,    25,     0,     2,     1,     0,    16,     0,    24,    35,
    23,    27,    73,    31,     0,    62,    32,    33,     0,    34,
     0,    28,     0,     0,     0,    65,    19,    62,     0,     0,
    66,    67,    68,     0,    82,    81,    80,     0,    22,    84,
    83,     0,     6,     0,    85,    30,    26,    29,    17,    21,
     0,    36,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    72,    86,     0,     0,     0,     0,     0,    65,     0,
    72,    65,     0,    15,     8,    14,     0,     4,    74,     0,
    41,    55,    56,    52,    54,    53,    61,    59,    58,    60,
     0,     0,     0,    91,    92,    90,    93,     0,     0,     0,
     0,     0,     0,     0,     0,    43,     0,     7,     3,     0,
    10,     0,    12,     0,     5,    57,    95,    94,     0,    89,
     0,     0,    38,    37,    42,    13,    65,     0,     9,     0,
    72,    96,    97,     0,     0,     0,     0,    11,     0,     0,
     0,     0,     0,     0,     0,    48,    50,    49,    51,    40,
    39,    44,    46,    45,    47,     0,     0,     0
};

static const short yydefgoto[] = {   176,
    21,   117,    23,    63,   112,   132,    97,    24,    25,    26,
    27,   118,    29,    30,    72,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    64,    40,    41,    42,   119,   120
};

static const short yypact[] = {    -7,
-32768,  -103,-32768,-32768,   -94,   -79,-32768,-32768,   130,-32768,
   -18,-32768,-32768,   -32,-32768,    37,-32768,   205,-32768,-32768,
   -45,-32768,   -44,-32768,-32768,   -14,    37,    -6,-32768,    89,
-32768,-32768,-32768,-32768,     4,   -69,-32768,-32768,   -11,-32768,
    -5,-32768,     5,    -2,    77,   -40,-32768,    85,    -1,   117,
-32768,-32768,-32768,     9,-32768,-32768,-32768,   -43,-32768,-32768,
-32768,     3,-32768,   117,-32768,-32768,-32768,-32768,-32768,-32768,
   -38,-32768,   117,   117,   117,   117,   117,   117,   117,   117,
   117,   -61,-32768,    86,   -72,    20,    21,    15,    26,    31,
   -72,-32768,    32,-32768,-32768,    30,    38,    40,-32768,    42,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
   174,    36,   117,-32768,-32768,-32768,    86,    39,    27,    43,
   117,   117,   -72,    36,    36,    36,    34,-32768,-32768,   140,
-32768,    49,    44,    45,-32768,-32768,-32768,    86,    86,-32768,
    50,    53,-32768,-32768,-32768,-32768,    52,    57,-32768,   183,
-32768,-32768,-32768,   -62,   -62,    36,    36,-32768,   -40,    60,
    62,    65,    66,    89,    89,    36,    36,    36,    36,-32768,
-32768,-32768,-32768,-32768,-32768,   190,   191,-32768
};

static const short yypgoto[] = {-32768,
-32768,    10,-32768,    96,-32768,    51,    68,   132,    88,-32768,
-32768,    91,-32768,-32768,  -153,-32768,-32768,   -41,   161,   -59,
   200,  -105,   -42,    -9,   -58,   -95,   -17,-32768,-32768,   -53
};


#define	YYLAST		340


static const short yytable[] = {    49,
    65,    87,     1,    90,    99,   133,   100,     1,    93,    22,
   170,   171,     2,   102,   103,   104,   105,   106,   107,   108,
   109,   110,     3,   113,    44,    22,    43,     3,    65,    55,
     4,     5,   113,    78,    88,     4,    22,     6,    56,    45,
    55,    57,    79,     7,   133,    80,     1,    13,     7,    56,
    15,    60,    57,   136,     8,    81,     2,   111,   161,   163,
    61,    55,    60,   137,   113,     9,     3,   159,    51,    13,
    56,    61,    15,    57,     4,     5,    95,    66,    67,   141,
   142,     6,    16,    60,   152,   153,    96,     7,   148,    10,
    28,    11,    61,    12,    10,     1,    52,    53,     8,    47,
    50,   134,    13,    54,    14,    15,    28,    73,    68,     9,
    74,   160,   162,    16,    69,     3,    70,    28,    82,    71,
    75,    17,    18,     4,    83,    84,    19,    85,    91,    20,
    94,    76,    98,    10,    77,    11,     7,    12,     8,     1,
   134,    65,   121,   122,   123,   124,    13,     8,    14,    15,
   125,   126,   114,   115,   116,   127,    16,   128,    58,     3,
   130,   138,   139,    96,   140,    17,    18,     4,   149,   150,
    19,   156,   154,    20,   151,   155,   157,    12,     8,   166,
     7,   167,    10,     1,   168,   169,    12,    78,    14,   177,
   178,     8,     1,   129,   146,    13,    79,    14,    15,    80,
   158,     8,   101,     3,    86,    17,    89,   -20,    48,    81,
    19,     4,     3,    20,    17,    46,     0,    12,     0,    19,
     4,     0,    20,     0,     7,     0,    10,     0,    14,     0,
    12,     0,     0,     7,     0,     8,     0,     0,     0,    13,
    12,    14,    15,   135,     8,    17,    92,     0,     0,     0,
    19,    14,     0,    20,     0,   143,   144,   145,    17,    46,
     0,     0,     0,    19,     0,     0,    20,     0,    17,   147,
    10,     0,     0,    19,    12,     0,    20,     0,     0,    10,
     0,     0,     0,    12,     0,    14,     0,   164,   165,     0,
     0,     0,     0,   131,    14,     0,     0,   172,   173,   174,
   175,     0,    17,    92,     0,     0,    55,    19,     0,     0,
    20,    17,    92,     0,    13,    56,    19,    15,    57,    20,
     0,     0,     0,    58,     0,     0,     0,    59,    60,     0,
     0,     0,     0,     0,     0,     0,     0,    61,     0,    62
};

static const short yycheck[] = {     9,
    18,    44,    10,    45,    64,   111,    45,    10,    50,     0,
   164,   165,    20,    73,    74,    75,    76,    77,    78,    79,
    80,    81,    30,    82,   119,    16,   130,    30,    46,   102,
    38,    39,    91,   103,    44,    38,    27,    45,   111,   119,
   102,   114,   112,    51,   150,   115,    10,   110,    51,   111,
   113,   124,   114,   113,    62,   125,    20,   119,   154,   155,
   133,   102,   124,   117,   123,    73,    30,   130,   101,   110,
   111,   133,   113,   114,    38,    39,   120,   123,   123,   121,
   122,    45,   121,   124,   138,   139,   130,    51,   130,    97,
     0,    99,   133,   101,    97,    10,   129,   130,    62,     9,
   119,   111,   110,    16,   112,   113,    16,   104,   123,    73,
   107,   154,   155,   121,    27,    30,   123,    27,   130,    31,
   117,   129,   130,    38,   130,   121,   134,   130,   130,   137,
   122,   128,   130,    97,   131,    99,    51,   101,    62,    10,
   150,   159,   123,   123,   130,   120,   110,    62,   112,   113,
   120,   120,    67,    68,    69,   126,   121,   120,   119,    30,
   119,   123,   136,   130,   122,   129,   130,    38,   120,   126,
   134,   120,   123,   137,   130,   123,   120,   101,    62,   120,
    51,   120,    97,    10,   120,   120,   101,   103,   112,     0,
     0,    62,    10,    98,   127,   110,   112,   112,   113,   115,
   150,    62,    71,    30,    44,   129,   130,   123,     9,   125,
   134,    38,    30,   137,   129,   130,    -1,   101,    -1,   134,
    38,    -1,   137,    -1,    51,    -1,    97,    -1,   112,    -1,
   101,    -1,    -1,    51,    -1,    62,    -1,    -1,    -1,   110,
   101,   112,   113,   112,    62,   129,   130,    -1,    -1,    -1,
   134,   112,    -1,   137,    -1,   124,   125,   126,   129,   130,
    -1,    -1,    -1,   134,    -1,    -1,   137,    -1,   129,   130,
    97,    -1,    -1,   134,   101,    -1,   137,    -1,    -1,    97,
    -1,    -1,    -1,   101,    -1,   112,    -1,   156,   157,    -1,
    -1,    -1,    -1,   120,   112,    -1,    -1,   166,   167,   168,
   169,    -1,   129,   130,    -1,    -1,   102,   134,    -1,    -1,
   137,   129,   130,    -1,   110,   111,   134,   113,   114,   137,
    -1,    -1,    -1,   119,    -1,    -1,    -1,   123,   124,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,   133,    -1,   135
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 154 "dlang.y"
{printf("Expressions list\n");;
    break;}
case 2:
#line 155 "dlang.y"
{printf("Block\n");;
    break;}
case 3:
#line 161 "dlang.y"
{printf("call method\n");;
    break;}
case 4:
#line 162 "dlang.y"
{printf("call attribute\n");;
    break;}
case 5:
#line 167 "dlang.y"
{printf("FUnction DEclaration\n ");;
    break;}
case 13:
#line 190 "dlang.y"
{printf("ID LIST");;
    break;}
case 14:
#line 191 "dlang.y"
{printf("ID");;
    break;}
case 15:
#line 197 "dlang.y"
{printf("Block: ");;
    break;}
case 18:
#line 207 "dlang.y"
{printf("Return Empty: ");;
    break;}
case 19:
#line 208 "dlang.y"
{printf("Return Assigment: ");;
    break;}
case 20:
#line 209 "dlang.y"
{printf("Return Literals: ");;
    break;}
case 21:
#line 213 "dlang.y"
{printf("Assign Expression\n");;
    break;}
case 22:
#line 214 "dlang.y"
{printf("ID Declaration\n");;
    break;}
case 23:
#line 215 "dlang.y"
{printf("While Delclaration\n");;
    break;}
case 24:
#line 216 "dlang.y"
{printf("If Delclaration\n");;
    break;}
case 25:
#line 217 "dlang.y"
{printf("Function Delclaration\n");;
    break;}
case 26:
#line 218 "dlang.y"
{printf("FUnction Usage Delclaration\n");;
    break;}
case 27:
#line 219 "dlang.y"
{printf("For Delclaration\n");;
    break;}
case 28:
#line 220 "dlang.y"
{printf("Clase Delclaration\n");;
    break;}
case 29:
#line 221 "dlang.y"
{printf("Return Delclaration\n");;
    break;}
case 30:
#line 222 "dlang.y"
{printf("Call to method/attribute  \n");;
    break;}
case 31:
#line 226 "dlang.y"
{printf("Type Assginment\n");;
    break;}
case 32:
#line 227 "dlang.y"
{printf("Normal Declaration\n");;
    break;}
case 33:
#line 228 "dlang.y"
{printf("Normal Declaration\n");;
    break;}
case 34:
#line 229 "dlang.y"
{printf("Increment/Decrementa Declaration\n");;
    break;}
case 35:
#line 233 "dlang.y"
{printf("IF-Only Declaration\n");;
    break;}
case 36:
#line 234 "dlang.y"
{printf("IF-Else Declaration\n");;
    break;}
case 37:
#line 238 "dlang.y"
{printf("IF Condition Declaration\n");;
    break;}
case 38:
#line 239 "dlang.y"
{printf("IF ID-Condition Declaration\n");;
    break;}
case 39:
#line 243 "dlang.y"
{printf("ELSE-IF Condition Declaration\n");;
    break;}
case 40:
#line 244 "dlang.y"
{printf("ELSE-IF ID Condition Declaration\n");;
    break;}
case 41:
#line 245 "dlang.y"
{printf("ELSE Declaration\n");;
    break;}
case 42:
#line 249 "dlang.y"
{printf("While Block: \n");;
    break;}
case 43:
#line 250 "dlang.y"
{printf("While: \n");;
    break;}
case 52:
#line 268 "dlang.y"
{printf("Greater than condition ");;
    break;}
case 53:
#line 269 "dlang.y"
{printf("Less than condition ");;
    break;}
case 54:
#line 270 "dlang.y"
{printf("Equal condition ");;
    break;}
case 55:
#line 271 "dlang.y"
{printf("AND condition ");;
    break;}
case 56:
#line 272 "dlang.y"
{printf("OR Operation ");;
    break;}
case 58:
#line 280 "dlang.y"
{printf("Plus Operation \n");;
    break;}
case 59:
#line 281 "dlang.y"
{printf("Minus Operation \n");;
    break;}
case 60:
#line 282 "dlang.y"
{printf("Multiply Operation \n");;
    break;}
case 61:
#line 283 "dlang.y"
{printf("Division Operation \n");;
    break;}
case 63:
#line 288 "dlang.y"
{printf("Literal Number ");;
    break;}
case 64:
#line 289 "dlang.y"
{printf("Literal Decimal ");;
    break;}
case 65:
#line 290 "dlang.y"
{printf("Literal ID ");;
    break;}
case 66:
#line 291 "dlang.y"
{printf("Literal Negative Number ");;
    break;}
case 67:
#line 292 "dlang.y"
{printf("Literal Negative Decimal ");;
    break;}
case 68:
#line 293 "dlang.y"
{printf("Literal Negative ID ");;
    break;}
case 69:
#line 294 "dlang.y"
{printf("Literal Char ");;
    break;}
case 70:
#line 295 "dlang.y"
{printf("Literal String ");;
    break;}
case 71:
#line 296 "dlang.y"
{printf("Null ");;
    break;}
case 75:
#line 309 "dlang.y"
{printf("Type Int ");;
    break;}
case 76:
#line 310 "dlang.y"
{printf("Type Double ");;
    break;}
case 77:
#line 311 "dlang.y"
{printf("Type Float ");;
    break;}
case 78:
#line 312 "dlang.y"
{printf("Type Bool ");;
    break;}
case 79:
#line 313 "dlang.y"
{printf("Type Void ");;
    break;}
case 80:
#line 317 "dlang.y"
{printf(" += ");;
    break;}
case 81:
#line 318 "dlang.y"
{printf(" -= ");;
    break;}
case 82:
#line 319 "dlang.y"
{printf(" /= ");;
    break;}
case 83:
#line 320 "dlang.y"
{printf(" *= ");;
    break;}
case 84:
#line 321 "dlang.y"
{printf(" = ");;
    break;}
case 85:
#line 324 "dlang.y"
{printf("ID INC/DEC ");;
    break;}
case 86:
#line 325 "dlang.y"
{printf("INC/DEC ID ");;
    break;}
case 87:
#line 328 "dlang.y"
{printf("Increment ");;
    break;}
case 88:
#line 329 "dlang.y"
{printf("Decrement ");;
    break;}
case 90:
#line 336 "dlang.y"
{printf("Publc ");;
    break;}
case 91:
#line 337 "dlang.y"
{printf("Private ");;
    break;}
case 92:
#line 338 "dlang.y"
{printf("Protected ");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 348 "dlang.y"

int yyerror(char const *s) {
	printf("\n\n%s\n",s);

}    




