/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 169
#define YY_END_OF_BUFFER 170
static yyconst short int yy_acclist[694] =
    {   0,
      170,  168,  169,    6,  168,  169,    7,  169,  138,  168,
      169,  168,  169,  164,  168,  169,  149,  168,  169,  155,
      168,  169,  117,  168,  169,  168,  169,  139,  168,  169,
      140,  168,  169,  153,  168,  169,  126,  168,  169,  146,
      168,  169,  123,  168,  169,  112,  168,  169,  114,  168,
      169,  166,  168,  169,  148,  168,  169,  147,  168,  169,
      130,  168,  169,  151,  168,  169,  136,  168,  169,  145,
      168,  169,  162,  168,  169,  167,  168,  169,  141,  168,
      169,  142,  168,  169,  159,  168,  169,  167,  168,  169,
      167,  168,  169,  167,  168,  169,  167,  168,  169,  167,

      168,  169,  167,  168,  169,  167,  168,  169,  167,  168,
      169,  167,  168,  169,  167,  168,  169,  167,  168,  169,
      167,  168,  169,  167,  168,  169,  167,  168,  169,  167,
      168,  169,  167,  168,  169,  167,  168,  169,  167,  168,
      169,  167,  168,  169,  143,  168,  169,  120,  168,  169,
      144,  168,  169,  161,  168,  169,    4,  169,    5,  169,
        4,  169,  137,  109,  154,  115,  116,  107,  152,  124,
      125,  121,  122,  111,    2,    1,  113,  166,  128,  129,
      150,  163,  135,  134,  167,  158,  157,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,

      167,  167,  167,  167,   34,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,   51,  167,  167,   58,
      167,  167,   60,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  119,  118,
      160,    3,  108,  109,  106,  110,    1,  165,  127,  133,
      132,  156,  167,  167,   11,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,

      167,  167,  167,  167,   46,  167,  167,  167,  167,  167,
      167,  167,  167,   56,  167,  167,  167,  167,  167,  167,
      167,   65,  167,  167,  167,   68,  167,  167,  167,  167,
      167,  167,  167,  167,  167,   77,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
       91,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  131,  167,  167,  167,  167,   13,
      167,   14,  167,   15,  167,  167,   17,  167,   18,  167,
       19,  167,  167,  167,   22,  167,  167,   24,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,   36,

      167,   37,  167,  167,  167,  167,  167,  167,  167,  167,
       48,  167,  167,  167,  167,  167,  167,  167,  167,  167,
       61,  167,   62,  167,  167,  167,  167,   67,  167,  167,
      167,  167,  167,  167,  167,   75,  167,   76,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,   88,
      167,  167,   90,  167,  167,  167,  167,   96,  167,  167,
      167,  167,  167,  167,  102,  167,  167,  167,  105,  167,
      167,    9,  167,   10,  167,  167,   16,  167,   20,  167,
      167,  167,   25,  167,   26,  167,  167,   28,  167,   29,
      167,   30,  167,  167,  167,  167,  167,  167,  167,   40,

      167,   42,  167,   43,  167,  167,  167,  167,  167,  167,
      167,   54,  167,  167,  167,   59,  167,   63,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,   79,  167,
      167,   81,  167,  167,  167,   84,  167,  167,  167,  167,
       89,  167,  167,  167,   94,  167,   95,  167,   97,  167,
       98,  167,  167,  167,  167,  103,  167,  104,  167,  167,
       12,  167,  167,   23,  167,  167,  167,  167,  167,   35,
      167,   38,  167,   39,  167,  167,  167,  167,  167,   50,
      167,  167,   53,  167,  167,  167,   64,  167,  167,  167,
      167,   71,  167,  167,  167,   74,  167,   78,  167,   80,

      167,   82,  167,   83,  167,   85,  167,  167,  167,   92,
      167,   93,  167,  167,  100,  167,  167,  167,   21,  167,
      167,   31,  167,  167,  167,   41,  167,   45,  167,  167,
       49,  167,  167,  167,  167,   66,  167,  167,   70,  167,
       72,  167,  167,  167,  167,  167,  101,  167,    8,  167,
       27,  167,   32,  167,  167,  167,   47,  167,  167,  167,
      167,   69,  167,  167,  167,   87,  167,   99,  167,  167,
      167,   52,  167,   55,  167,   57,  167,   73,  167,  167,
       33,  167,  167,  167,  167,  167,  167,   86,  167,  167,
      167,   44,  167

    } ;

static yyconst short int yy_accept[502] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   12,
       14,   17,   20,   23,   26,   28,   31,   34,   37,   40,
       43,   46,   49,   52,   55,   58,   61,   64,   67,   70,
       73,   76,   79,   82,   85,   88,   91,   94,   97,  100,
      103,  106,  109,  112,  115,  118,  121,  124,  127,  130,
      133,  136,  139,  142,  145,  148,  151,  154,  157,  159,
      161,  163,  164,  164,  164,  165,  166,  167,  168,  169,
      169,  169,  170,  171,  172,  173,  174,  175,  176,  177,
      178,  178,  179,  180,  181,  182,  183,  184,  185,  186,
      187,  188,  189,  190,  191,  192,  193,  194,  195,  196,

      197,  198,  199,  200,  201,  202,  203,  204,  205,  207,
      208,  209,  210,  211,  212,  213,  214,  215,  216,  217,
      219,  220,  222,  223,  225,  226,  227,  228,  229,  230,
      231,  232,  233,  234,  235,  236,  237,  238,  239,  240,
      241,  242,  243,  244,  245,  246,  247,  248,  249,  250,
      251,  252,  253,  254,  255,  256,  257,  258,  259,  260,
      261,  262,  263,  263,  265,  266,  267,  268,  269,  270,
      271,  272,  273,  274,  275,  277,  278,  279,  280,  281,
      282,  283,  284,  285,  286,  287,  288,  289,  290,  291,
      292,  293,  294,  295,  296,  297,  298,  299,  300,  301,

      302,  303,  304,  305,  307,  308,  309,  310,  311,  312,
      313,  314,  316,  317,  318,  319,  320,  321,  322,  324,
      325,  326,  328,  329,  330,  331,  332,  333,  334,  335,
      336,  338,  339,  340,  341,  342,  343,  344,  345,  346,
      347,  348,  349,  350,  351,  353,  354,  355,  356,  357,
      358,  359,  360,  361,  362,  363,  364,  365,  366,  367,
      368,  369,  370,  372,  374,  376,  377,  379,  381,  383,
      384,  385,  387,  388,  390,  391,  392,  393,  394,  395,
      396,  397,  398,  399,  400,  402,  404,  405,  406,  407,
      408,  409,  410,  411,  413,  414,  415,  416,  417,  418,

      419,  420,  421,  423,  425,  426,  427,  428,  430,  431,
      432,  433,  434,  435,  436,  438,  440,  441,  442,  443,
      444,  445,  446,  447,  448,  449,  450,  452,  453,  455,
      456,  457,  458,  460,  461,  462,  463,  464,  465,  467,
      468,  469,  471,  472,  474,  476,  477,  479,  481,  482,
      483,  485,  487,  488,  490,  492,  494,  495,  496,  497,
      498,  499,  500,  502,  504,  506,  507,  508,  509,  510,
      511,  512,  514,  515,  516,  518,  520,  521,  522,  523,
      524,  525,  526,  527,  528,  529,  531,  532,  534,  535,
      536,  538,  539,  540,  541,  543,  544,  545,  547,  549,

      551,  553,  554,  555,  556,  558,  560,  561,  563,  564,
      566,  567,  568,  569,  570,  572,  574,  576,  577,  578,
      579,  580,  582,  583,  585,  586,  587,  589,  590,  591,
      592,  594,  595,  596,  598,  600,  602,  604,  606,  608,
      609,  610,  612,  614,  615,  617,  618,  619,  621,  622,
      624,  625,  626,  628,  630,  631,  633,  634,  635,  636,
      638,  639,  641,  643,  644,  645,  646,  647,  649,  651,
      653,  655,  656,  657,  659,  660,  661,  662,  664,  665,
      666,  668,  670,  671,  672,  674,  676,  678,  680,  681,
      683,  684,  685,  686,  687,  688,  690,  691,  692,  694,

      694
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,    1,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   27,   41,   42,   43,   44,
       45,   46,   27,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[60] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    4,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[505] =
    {   0,
        0,    0,   57,   58,  622,  623,  623,  623,  598,   71,
      623,  623,  597,  122,   55,  623,  623,  596,  118,  623,
       46,  601,  120,   47,  623,  623,   45,  111,  113,  623,
      623,    0,  623,  623,  116,  107,   97,  124,  128,  123,
      138,  572,  142,  136,  107,  146,  103,  152,  580,  158,
      159,  181,  158,  177,  623,  152,  623,  592,  623,  623,
      596,  623,  228,  282,    0,  623,  623,  623,  623,  603,
      602,  623,  623,  623,  623,  623,  594,  623,    0,  623,
      591,  131,  586,  623,  623,  623,  623,  177,    0,  623,
      585,  559,  566,  176,  556,  183,  568,  554,  156,  557,

      557,  558,  567,  566,  553,  560,  556,  189,  544,  545,
      542,  187,  549,  546,  544,  541,  543,  537,  540,  542,
      191,  193,  547,    0,  527,  537,  527,  544,  526,  528,
      534,  526,  538,  539,  200,  125,  209,  527,  142,  207,
      525,  530,  525,  525,  180,  193,  521,  512,  529,  520,
      518,  522,  522,  513,  519,  519,  517,  507,  623,  623,
      623,  623,    0,    0,  623,  623,    0,  536,  623,  623,
      531,  623,  504,  218,    0,  516,  506,  496,  507,  516,
      511,  249,  512,  495,  495,  498,  495,  493,  200,  508,
      507,  488,  505,  500,  488,  501,  497,  489,  486,  494,

      481,  496,  495,  490,  491,  479,  473,  477,  471,  475,
      469,  482,  485,  484,  461,  476,  473,  462,    0,  472,
      468,    0,  462,  467,  469,  455,  456,  462,  467,  460,
        0,  451,  454,  452,  451,  448,  446,  459,  445,  459,
      446,  443,  445,  453,    0,  452,  438,  442,  436,  440,
      208,  438,  434,  446,  448,  437,  439,  623,  430,  428,
      431,  427,    0,    0,    0,  432,    0,    0,    0,  433,
      438,    0,  438,    0,  421,  419,  427,  424,  418,  426,
      413,  424,  425,  418,    0,    0,  412,  411,  421,  414,
      406,  422,  404,    0,  419,  419,  401,  402,  399,  400,

      399,  403,    0,    0,  400,  401,  395,    0,  394,  408,
      396,  406,  401,  396,    0,    0,  388,  398,  397,  383,
      391,  396,  382,  394,  388,  384,    0,  373,    0,  246,
      388,  374,    0,  384,  377,  371,  372,  378,    0,  370,
      380,    0,  383,    0,    0,  365,    0,    0,  371,  363,
        0,    0,  367,    0,    0,    0,  368,  377,  374,  371,
      357,  361,    0,  362,    0,  369,  362,  359,  351,  367,
      349,    0,  360,  356,    0,    0,  359,  349,  353,  354,
      359,  341,  355,  354,  343,    0,  351,    0,  351,  335,
        0,  344,  335,  349,    0,  345,  342,    0,    0,    0,

        0,  342,  328,  331,    0,    0,  341,    0,  338,    0,
      323,  323,  322,  338,    0,    0,    0,  315,  329,  322,
      330,    0,  332,    0,  332,  331,    0,  310,  326,  324,
        0,  323,  309,    0,    0,    0,    0,    0,    0,  312,
      307,    0,    0,  307,    0,  310,  304,    0,  316,    0,
      315,  301,    0,  318,  304,    0,  303,  278,  267,    0,
      274,    0,    0,  272,  263,  270,  256,    0,    0,    0,
        0,  268,  256,    0,  266,  264,  250,    0,  262,  256,
        0,    0,  260,  258,    0,    0,    0,    0,  238,    0,
      241,  254,  253,  253,  205,    0,  203,  157,    0,  623,

      337,  339,   59,  343
    } ;

static yyconst short int yy_def[505] =
    {   0,
      500,    1,  501,  501,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  502,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  503,  500,  500,  500,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  500,  500,  500,  500,  500,  500,
      500,  500,   10,   10,   63,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  504,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  503,  500,
      500,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  500,  500,
      500,  500,   64,   63,  500,  500,  504,  500,  500,  500,
      500,  500,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  500,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,    0,

      500,  500,  500,  500
    } ;

static yyconst short int yy_nxt[683] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       32,   36,   37,   38,   39,   40,   41,   42,   32,   43,
       32,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   32,   32,   32,   55,   56,   57,   58,   60,
       60,   75,   89,   81,   69,   82,   83,   84,   76,   61,
       61,   63,   64,   70,   63,   65,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   64,   63,   63,

       63,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   63,   63,   63,   63,
       67,   73,   78,   85,   86,   87,   88,   79,   90,   92,
       74,   96,   80,   97,   68,   91,  127,   81,   93,   82,
       98,  128,  132,  133,   94,   99,   95,  228,  100,  101,
      102,  107,  103,  108,  110,  104,  111,  125,  105,  113,
      106,  229,  109,  234,  159,  112,  119,  114,  120,  115,
      126,  129,  116,  134,  121,  122,  235,  117,  123,  124,
      130,  138,  499,  154,  144,  131,  139,  145,  135,  170,

      171,  136,  155,  182,  183,  146,  140,  141,  160,  142,
      156,  143,  147,  148,  149,  157,  158,  178,  175,  242,
      150,  192,  151,  176,  152,  193,  243,  179,  153,   63,
      194,  225,  199,  209,  195,  200,  210,  211,  236,  226,
      230,  212,  244,  213,  227,  231,  245,  276,  277,  260,
      498,  497,  335,  237,   63,  261,  336,  232,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,  163,  268,  396,  164,  496,  495,  494,
      397,  493,  492,  491,  490,  489,  488,  269,  487,  486,

      163,  485,  484,  483,  482,  481,  480,  479,  163,  478,
      477,  476,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,   59,   59,   59,
       59,   71,   71,  167,  475,  167,  167,  474,  473,  472,
      471,  470,  469,  468,  467,  466,  465,  464,  463,  462,
      461,  460,  459,  458,  457,  456,  455,  454,  453,  452,
      451,  450,  449,  448,  447,  446,  445,  444,  443,  442,
      441,  440,  439,  438,  437,  436,  435,  434,  433,  432,
      431,  430,  429,  428,  427,  426,  425,  424,  423,  422,

      421,  420,  419,  418,  417,  416,  415,  414,  413,  412,
      411,  410,  409,  408,  407,  406,  405,  404,  403,  402,
      401,  400,  399,  398,  395,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  338,  337,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,

      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      275,  274,  273,  272,  271,  270,  267,  266,  265,  264,
      263,  262,  259,  258,  168,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  241,  240,  239,
      238,  233,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  208,  207,  206,  205,  204,  203,  202,
      201,  198,  197,  196,  191,  190,  189,  188,  187,  186,

      185,  184,  181,  180,  177,  174,  173,  172,  169,  168,
      166,  165,   69,  162,  161,  137,  118,   77,   72,   66,
       62,  500,    5,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500
    } ;

static yyconst short int yy_chk[683] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,   21,  503,   24,   15,   24,   27,   27,   21,    3,
        4,   10,   10,   15,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       14,   19,   23,   28,   28,   29,   29,   23,   35,   36,
       19,   37,   23,   37,   14,   35,   45,   82,   36,   82,
       37,   45,   47,   47,   36,   38,   36,  136,   38,   38,
       38,   39,   38,   39,   40,   38,   40,   44,   38,   41,
       38,  136,   39,  139,   56,   40,   43,   41,   43,   41,
       44,   46,   41,   48,   43,   43,  139,   41,   43,   43,
       46,   50,  498,   53,   51,   46,   50,   51,   48,   88,

       88,   48,   53,   99,   99,   51,   50,   50,   56,   50,
       54,   50,   51,   52,   52,   54,   54,   96,   94,  145,
       52,  108,   52,   94,   52,  108,  145,   96,   52,   63,
      108,  135,  112,  121,  108,  112,  121,  122,  140,  135,
      137,  122,  146,  122,  135,  137,  146,  189,  189,  174,
      497,  495,  251,  140,   63,  174,  251,  137,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   64,  182,  330,   64,  494,  493,  492,
      330,  491,  489,  484,  483,  480,  479,  182,  477,  476,

       64,  475,  473,  472,  467,  466,  465,  464,   64,  461,
      459,  458,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,  501,  501,  501,
      501,  502,  502,  504,  457,  504,  504,  455,  454,  452,
      451,  449,  447,  446,  444,  441,  440,  433,  432,  430,
      429,  428,  426,  425,  423,  421,  420,  419,  418,  414,
      413,  412,  411,  409,  407,  404,  403,  402,  397,  396,
      394,  393,  392,  390,  389,  387,  385,  384,  383,  382,
      381,  380,  379,  378,  377,  374,  373,  371,  370,  369,

      368,  367,  366,  364,  362,  361,  360,  359,  358,  357,
      353,  350,  349,  346,  343,  341,  340,  338,  337,  336,
      335,  334,  332,  331,  328,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  314,  313,  312,  311,  310,
      309,  307,  306,  305,  302,  301,  300,  299,  298,  297,
      296,  295,  293,  292,  291,  290,  289,  288,  287,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  273,
      271,  270,  266,  262,  261,  260,  259,  257,  256,  255,
      254,  253,  252,  250,  249,  248,  247,  246,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,

      232,  230,  229,  228,  227,  226,  225,  224,  223,  221,
      220,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      188,  187,  186,  185,  184,  183,  181,  180,  179,  178,
      177,  176,  173,  171,  168,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  144,  143,  142,
      141,  138,  134,  133,  132,  131,  130,  129,  128,  127,
      126,  125,  123,  120,  119,  118,  117,  116,  115,  114,
      113,  111,  110,  109,  107,  106,  105,  104,  103,  102,

      101,  100,   98,   97,   95,   93,   92,   91,   83,   81,
       77,   71,   70,   61,   58,   49,   42,   22,   18,   13,
        9,    5,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "dlang.l"
#define INITIAL 0
#define C_COMMENT 1

#line 7 "dlang.l"
	#include "dlang.tab.h"


	
#line 782 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 13 "dlang.l"

#line 946 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 501 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 623 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 14 "dlang.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 15 "dlang.l"
{ BEGIN(C_COMMENT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 16 "dlang.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 17 "dlang.l"
{ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 18 "dlang.l"
{ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 19 "dlang.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 20 "dlang.l"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 21 "dlang.l"
{ return T_abstract;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 22 "dlang.l"
{ return T_alias;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 23 "dlang.l"
{ return T_align;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 24 "dlang.l"
{ return T_asm;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 25 "dlang.l"
{ return T_assert;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 26 "dlang.l"
{ return T_auto;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 27 "dlang.l"
{ return T_body;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 28 "dlang.l"
{ return T_bool;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 29 "dlang.l"
{ return T_break;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 30 "dlang.l"
{ return T_byte;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 31 "dlang.l"
{ return T_case;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 32 "dlang.l"
{ return T_cast;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 33 "dlang.l"
{ return T_catch;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 34 "dlang.l"
{ return T_cdouble;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 35 "dlang.l"
{ return T_cent;}           
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 36 "dlang.l"
{ return T_cfloat;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 37 "dlang.l"
{ return T_char;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 38 "dlang.l"
{ return T_class;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 39 "dlang.l"
{ return T_const;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 40 "dlang.l"
{ return T_continue;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 41 "dlang.l"
{ return T_creal;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 42 "dlang.l"
{ return T_dchar;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 43 "dlang.l"
{ return T_debug;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 44 "dlang.l"
{ return T_default;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 45 "dlang.l"
{ return T_delegate;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 46 "dlang.l"
{ return T_deprecated;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 47 "dlang.l"
{ return T_do;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 48 "dlang.l"
{ return T_double;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 49 "dlang.l"
{ return T_else;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 50 "dlang.l"
{ return T_enum;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 51 "dlang.l"
{ return T_export;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 52 "dlang.l"
{ return T_extern;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 53 "dlang.l"
{ return T_false;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 54 "dlang.l"
{ return T_finally;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 55 "dlang.l"
{ return T_final;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 56 "dlang.l"
{ return T_float;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 57 "dlang.l"
{ return T_foreach_reverse;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 58 "dlang.l"
{ return T_foreach;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 59 "dlang.l"
{ return T_for;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 60 "dlang.l"
{ return T_function;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 61 "dlang.l"
{ return T_goto;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 62 "dlang.l"
{return T_idouble;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 63 "dlang.l"
{return T_ifloat;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 64 "dlang.l"
{return T_if;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 65 "dlang.l"
{return T_immutable;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 66 "dlang.l"
{return T_import;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 67 "dlang.l"
{return T_inout;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 68 "dlang.l"
{return T_interface;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 69 "dlang.l"
{return T_int;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 70 "dlang.l"
{return T_invariant;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 71 "dlang.l"
{return T_in;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 72 "dlang.l"
{return T_ireal;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 73 "dlang.l"
{return T_is;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 74 "dlang.l"
{return T_lazy;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 75 "dlang.l"
{return T_long;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 76 "dlang.l"
{return T_mixin;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 77 "dlang.l"
{return T_module;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 78 "dlang.l"
{return T_new;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 79 "dlang.l"
{return T_nothrow;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 80 "dlang.l"
{return T_null;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 81 "dlang.l"
{return T_out;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 82 "dlang.l"
{return T_override;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 83 "dlang.l"
{return T_package;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 84 "dlang.l"
{return T_pragma;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 85 "dlang.l"
{return T_private;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 86 "dlang.l"
{return T_protected;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 87 "dlang.l"
{return T_public;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 88 "dlang.l"
{return T_pure;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 89 "dlang.l"
{return T_real;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 90 "dlang.l"
{return T_ref;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 91 "dlang.l"
{return T_return;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 92 "dlang.l"
{return T_scope;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 93 "dlang.l"
{return T_shared;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 94 "dlang.l"
{return T_short;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 95 "dlang.l"
{return T_static;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 96 "dlang.l"
{return T_struc;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 97 "dlang.l"
{return T_super;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 98 "dlang.l"
{return T_switch;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 99 "dlang.l"
{return T_synchronized;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 100 "dlang.l"
{return T_template;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 101 "dlang.l"
{return T_this;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 102 "dlang.l"
{return T_throw;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 103 "dlang.l"
{return T_true;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 104 "dlang.l"
{return T_try;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 105 "dlang.l"
{return T_typeid;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 106 "dlang.l"
{return T_typeof;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 107 "dlang.l"
{return T_ubyte;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 108 "dlang.l"
{return T_ucent;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 109 "dlang.l"
{return T_uint;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 110 "dlang.l"
{return T_ulong;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 111 "dlang.l"
{return T_union;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 112 "dlang.l"
{return T_unittest;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 113 "dlang.l"
{return T_ushort;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 114 "dlang.l"
{return T_version;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 115 "dlang.l"
{return T_void;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 116 "dlang.l"
{return T_wchar;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 117 "dlang.l"
{return T_while;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 118 "dlang.l"
{return T_with;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 120 "dlang.l"
{printf("<char literal, %s>\n",yytext); return T_LITCHAR;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 121 "dlang.l"
{printf("<char literal, %s>\n",yytext); return T_LITCHAR;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 122 "dlang.l"
{printf("<string literal, %s>",yytext); return T_LSTRING;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 123 "dlang.l"
{printf("<string literal, %s>\n",yytext); return T_LSTRING;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 125 "dlang.l"
{}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 126 "dlang.l"
{}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 127 "dlang.l"
{ return T_dot;}                                                     
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 128 "dlang.l"
{return T_neq;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 129 "dlang.l"
{return T_bslash;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 130 "dlang.l"
{return T_land;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 131 "dlang.l"
{return T_andeq;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 132 "dlang.l"
{return T_and;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 133 "dlang.l"
{return T_lor;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 134 "dlang.l"
{return T_oreq;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 135 "dlang.l"
{return T_or;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 136 "dlang.l"
{return T_dec;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 137 "dlang.l"
{return T_deceq;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 138 "dlang.l"
{return T_minus;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 139 "dlang.l"
{return T_inc;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 140 "dlang.l"
{return T_inceq;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 141 "dlang.l"
{return T_plus;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 143 "dlang.l"
{}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 144 "dlang.l"
{}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 145 "dlang.l"
{ return T_LE;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 146 "dlang.l"
{ return T_LT;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 147 "dlang.l"
{}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 148 "dlang.l"
{}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 149 "dlang.l"
{}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 150 "dlang.l"
{}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 152 "dlang.l"
{ return T_GEQ;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 153 "dlang.l"
{ return T_GR;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 154 "dlang.l"
{ return T_NOTEQ;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 155 "dlang.l"
{}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 156 "dlang.l"
{ return T_OPAREN;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 157 "dlang.l"
{ return T_CPAREN;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 158 "dlang.l"
{}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 159 "dlang.l"
{}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 160 "dlang.l"
{ return T_OCOR;}	
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 161 "dlang.l"
{ return T_CCOR;}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 163 "dlang.l"
{}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 164 "dlang.l"
{return T_COMA;}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 165 "dlang.l"
{return T_SEMICOLON;}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 166 "dlang.l"
{ return T_COLON;}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 168 "dlang.l"
{}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 169 "dlang.l"
{ return T_isEqual;}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 170 "dlang.l"
{ return T_EQUAL;}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 171 "dlang.l"
{ return T_multeq;}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 172 "dlang.l"
{return T_multiply;}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 173 "dlang.l"
{}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 174 "dlang.l"
{}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 176 "dlang.l"
{}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 177 "dlang.l"
{}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 178 "dlang.l"
{}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 179 "dlang.l"
{}
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 180 "dlang.l"
{}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 181 "dlang.l"
{}
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 182 "dlang.l"
{}
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 183 "dlang.l"
{}
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 184 "dlang.l"
{}
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 187 "dlang.l"
{printf("<float, %s>\n",yytext);return DEC;}
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 188 "dlang.l"
{printf("<integer, %s>\n",yytext);return NUM;}
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 189 "dlang.l"
{return ID;}
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 190 "dlang.l"
{printf(" LEXICAL ERROR on Line %d \n",yylineno); return 1;}
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 191 "dlang.l"
ECHO;
	YY_BREAK
#line 1882 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(C_COMMENT):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 501 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 501 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 500);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 191 "dlang.l"

#include <stdio.h>


